wexplorer/explorer/models.py
# -*- coding: utf-8 -*-

from wexplorer.database import (
    Column,
    db,
    Model
)

from wexplorer.extensions import bcrypt

class FileUploadPassword(Model):
    __tablename__ = 'file_upload_password'
    password = Column(db.String(128), nullable=False, primary_key=True)

    def __init__(self, password):
        if password:
            self.password = bcrypt.generate_password_hash(password)
        else:
            raise Exception('File Upload Password must be supplied')

class LastUpdated(Model):
    __tablename__ = 'last_updated'
    last_updated = Column(db.DateTime, primary_key=True)

    def __init__(self, last_updated):
        self.last_updated = last_updated

class Company(Model):
    __tablename__ = 'company'
    row_id = Column(db.Integer)
    company_id = Column(db.String(32), primary_key=True)
    company = Column(db.String(255))
    bus_type = Column(db.String(255))
    company_contacts = db.relationship('CompanyContact', backref='company', lazy='joined')
    contracts = db.relationship('Contract', backref='company', lazy='joined')

class CompanyContact(Model):
    __tablename__ = 'company_contact'
    row_id = Column(db.Integer)
    company_contact_id = Column(db.String(32), primary_key=True)
    contact_name = Column(db.String(255))
    address_1 = Column(db.String(255))
    address_2 = Column(db.String(255))
    phone_number = Column(db.String(255))
    fax_number = Column(db.String(255))
    email = Column(db.String(255))
    fin = Column(db.String(255))
    company_id = Column(db.String(32), db.ForeignKey('company.company_id'))

class Contract(Model):
    __tablename__ = 'contract'
    row_id = Column(db.Integer)
    contract_id = Column(db.String(32), primary_key=True)
    description = Column(db.Text)
    notes = Column(db.Text)
    county = Column(db.String(255))
    type_of_contract = Column(db.String(255))
    pa = Column(db.String(255))
    expiration = Column(db.DateTime)
    contract_number = Column(db.String(255))
    controller_number = Column(db.Integer)
    commcode = Column(db.Integer)
    company_id = Column(db.String(32), db.ForeignKey('company.company_id'))

wexplorer/user/models.py
# -*- coding: utf-8 -*-
import datetime as dt

from flask.ext.login import UserMixin

from wexplorer.extensions import bcrypt
from wexplorer.database import (
    Column,
    db,
    Model,
    ReferenceCol,
    relationship,
    SurrogatePK,
)


class Role(SurrogatePK, Model):
    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = ReferenceCol('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        return '<Role({name})>'.format(name=self.name)

class User(UserMixin, SurrogatePK, Model):

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    def __repr__(self):
        return '<User({username!r})>'.format(username=self.username)

wexplorer/explorer/forms.py
# -*- coding: utf-8 -*-

from flask.ext.uploads import UploadSet
from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import TextField, PasswordField, ValidationError, BooleanField
from wtforms.validators import DataRequired

from wexplorer.extensions import bcrypt
from wexplorer.explorer.models import FileUploadPassword

class SearchBox(Form):
    q = TextField('Search', validators=[DataRequired()])
    expiring = BooleanField('Expiring Contracts')
    expired = BooleanField('Expired Contracts')

    def __init__(self, *args, **kwargs):
        super(SearchBox, self).__init__(*args, **kwargs)

class NewItemBox(Form):
    item = TextField('New Item', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(NewItemBox, self).__init__(*args, **kwargs)

class FileUpload(Form):
    upload = FileField('datafile', validators=[
        FileRequired(),
        FileAllowed(['xls', 'xlsx'], '.xls and .xlsx files only')
    ])
    password = PasswordField('Password',
                                validators=[DataRequired()])

    def validate_password(form, field):
        current_password = FileUploadPassword.query.first()
        if not bcrypt.check_password_hash(current_password.password, field.data):
            raise ValidationError('File upload password incorrect')

wexplorer/shared/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired

from wexplorer.user.models import User

class LoginForm(Form):
    username = TextField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(LoginForm, self).validate()
        if not initial_validation:
            return False

        self.user = User.query.filter_by(username=self.username.data).first()
        if not self.user:
            self.username.errors.append('Unknown username')
            return False

        if not self.user.check_password(self.password.data):
            self.password.errors.append('Invalid password')
            return False

        if not self.user.active:
            self.username.errors.append('User not activated')
            return False
        return True

wexplorer/user/forms.py
from flask_wtf import Form
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User

class RegisterForm(Form):
    username = TextField('Username',
                    validators=[DataRequired(), Length(min=3, max=25)])
    email = TextField('Email',
                    validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                                validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append("Username already registered")
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        return True

wexplorer/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''
from flask import Flask, render_template

from wexplorer.settings import ProdConfig, DevConfig
from wexplorer.assets import assets
from wexplorer.extensions import (
    bcrypt,
    cache,
    db,
    login_manager,
    migrate,
    debug_toolbar,
)
from wexplorer.utils import url_for_other_page
from wexplorer import shared, user, explorer
from wexplorer.redirect import blueprint as redirect_bp

def create_app(config_object=DevConfig):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    return app

def register_extensions(app):
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    app.jinja_env.globals['url_for_other_page'] = url_for_other_page
    return None

def register_blueprints(app):
    # app.register_blueprint(shared.views.blueprint)
    # app.register_blueprint(explorer.views.blueprint)
    app.register_blueprint(redirect_bp)
    return None

def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

wexplorer/data_update/__init__.py
from update import update

wexplorer/explorer/__init__.py
# -*- coding: utf-8 -*-

'''The explorer module'''

from . import views

wexplorer/explorer/views.py
# -*- coding: utf-8 -*-
import datetime
import time
import re
import os
from werkzeug import secure_filename
from flask import (
    Blueprint, render_template, request,
    current_app, jsonify
)
from sqlalchemy.orm import load_only

from wexplorer.database import db
from wexplorer.explorer.models import (
    Company, CompanyContact, Contract, LastUpdated
)
from wexplorer.explorer.util import SimplePagination
from wexplorer.explorer.forms import SearchBox, NewItemBox, FileUpload
from wexplorer.data_update import update

blueprint = Blueprint('explorer', __name__, url_prefix='/explore',
                      static_folder="../static")

@blueprint.route('/', methods=['GET', 'POST'])
def search():
    '''
    The view for the basic search box.
    '''
    form = SearchBox(request.form)

    if request.args.get('q') is None:
        return render_template('explorer/explore.html', form=form)

    results = []
    search_for = request.args.get('q')
    page = int(request.args.get('page', 1))
    lower_bound = (page - 1) * 50
    upper_bound = lower_bound + 50

    companies = db.session.execute(
        '''
        SELECT a.company_id, b.contract_id, a.company, b.description
        FROM company a
        INNER JOIN contract b
        ON a.company_id = b.company_id
        WHERE a.company ilike :search_for_wc
        OR b.description ilike :search_for_wc
        OR b.controller_number::VARCHAR = :search_for
        OR b.contract_number ilike :search_for_wc
        ORDER BY a.company, b.description
        ''',
        {
            'search_for_wc': '%' + str(search_for)   + '%',
            'search_for': search_for,
        }
    ).fetchall()

    pagination = SimplePagination(page, 50, len(companies))

    for company in companies[lower_bound:upper_bound]:
        results.append({
            'company_id': company[0],
            'contract_id': company[1],
            'name': company[2],
            'description': company[3]
        })

    if len(results) == 0:
        results = None

    updated = LastUpdated.query.first()
    if updated:
        last_updated = datetime.datetime.strftime(
            LastUpdated.query.first().last_updated, '%b %d %Y'
        )
    else:
        last_updated = None

    return render_template(
        'explorer/explore.html', form=form, names=results, pagination=pagination, last_updated=last_updated
    )

@blueprint.route('/companies/<company_id>', methods=['GET', 'POST'])
def companies(company_id, page=1):
    '''
    Simple profile page for companies
    '''
    iform = NewItemBox()
    page = int(request.args.get('page', 1))

    company = Company.query.filter(
        Company.company_id == company_id
    ).distinct().first()

    contacts = CompanyContact.query.distinct(
        CompanyContact.contact_name, CompanyContact.address_1,
        CompanyContact.address_2, CompanyContact.phone_number,
        CompanyContact.email,
    ).options(
        load_only(
            'contact_name', 'address_1', 'address_2', 'phone_number', 'email'
        )
    ).filter(CompanyContact.company_id == company_id).all()

    return render_template(
        'explorer/companies.html',
        company=company,
        contacts=contacts,
        form=SearchBox(),
        iform=iform
    )

@blueprint.route('/contracts/<contract_id>', methods=['GET'])
def contracts(contract_id):
    '''
    Simple profile page for individual contracts
    '''
    form = SearchBox(request.form)

    company = Company.query.join(Contract).filter(
        Contract.contract_id == contract_id
    ).first()

    contract = company.contracts[0]
    contract_href = None
    if contract.contract_number and contract.type_of_contract.lower() == 'county':
        # first try to convert it to an int
        try:
            _contract_number = int(float(contract.contract_number))
            contract.contract_number = _contract_number
        # if you can't, it has * or other characters, so just
        # strip down to the digits
        except ValueError:
            if '**' in contract.contract_number:
                _contract_number = int(re.sub(r'i?\D', '', contract.contract_number))
            elif '*' in contract.contract_number:
                _contract_number = None
            elif 'i' in contract.contract_number:
                _contract_number = contract.contract_number


        # take the result and stick it into the well-formed county urls
        contract_href = 'http://apps.county.allegheny.pa.us/BidsSearch/pdf/{number}.pdf'.format(
            number=_contract_number
        ) if _contract_number else None

    return render_template(
        'explorer/contracts.html',
        company=company,
        contract=contract,
        form=form,
        contract_href=contract_href
    )

@blueprint.route('/upload_new', methods=['GET', 'POST'])
def upload():
    form = FileUpload()
    if form.validate_on_submit():
        _file = request.files.get('upload')
        filename = secure_filename(_file.filename)
        filepath = os.path.join(current_app.config.get('UPLOAD_FOLDER'), filename)
        _file.save(filepath)
        return render_template('explorer/upload_success.html', filepath=filepath)
    else:
        return render_template('explorer/upload_new.html', form=form)

@blueprint.route('/_process_file', methods=['POST'])
def process_upload():
    filepath = request.form.get('filepath')
    result = update(filepath)
    if result.get('status') == 'success':
        last_updated = LastUpdated.query.first()
        if not last_updated:
            last_updated = LastUpdated(datetime.datetime.utcnow())
            db.session.add(last_updated)
        else:
            last_updated.last_updated = datetime.datetime.utcnow()
        db.session.commit()
        return jsonify(result), 200
    else:
        return jsonify(result), 403

@blueprint.route('/_status')
def check_status():
    response = {}
    response['status'] = 'ok'
    try:
        Contract.query.first()
    except:
        response['status'] = 'Database is unavailable'
    response['updated'] = int(time.time())
    response['dependencies'] = []
    return jsonify(response)

wexplorer/shared/__init__.py
# -*- coding: utf-8 -*-
'''The public module, including the homepage and user auth.'''

from . import views

wexplorer/shared/views.py
# -*- coding: utf-8 -*-
'''Public section, including homepage and signup.'''
from flask import (Blueprint, request, render_template, flash, url_for,
                    redirect, session)

from wexplorer.database import db
from wexplorer.explorer.forms import SearchBox

blueprint = Blueprint('shared', __name__, static_folder="../static")

@blueprint.route("/", methods=["GET", "POST"])
def home():
    return redirect(url_for('explorer.search'))

@blueprint.route("/about")
def about():
    form = SearchBox()
    return render_template("shared/about.html", form=form)

wexplorer/user/__init__.py
'''The user module.'''

from . import views

wexplorer/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template
from flask.ext.login import login_required

blueprint = Blueprint("user", __name__, url_prefix='/users',
                        static_folder="../static")


@blueprint.route("/")
@login_required
def members():
    return render_template("users/members.html")

wexplorer/templates/explorer/big_search.html
<div class="row text-center">

  {% include "shared/big_logo.html" %}

  <h2>helps you find goods and services</h2>
  <h2 class="text-muted padded-bottom h2-mobile-fixed-two-rows"><strong id="js-cycle-phrases">for the lowest price.</strong></h2>

  <form id="search-box" method="GET" class="form form-inline" action="/explore/" role="login">
    <div class="form-group">
      {{ form.q(placeholder="I'm looking for...", class_="form-control input-lg") }}
    </div>
    <input class="btn btn-default btn-success input-lg" type="submit" value="Search">
  </form>

  <div class="spacer-20"></div>

  <h4 class="text-muted">
    Search company names, contract descriptions, controller numbers, <br />
    spec numbers, or items that have been entered into Wexplorer.
  </h4>

</div>

wexplorer/templates/explorer/companies.html
{% extends "layout.html" %}
{% block content %}

<div class="row">
  <div class="col-md-3">
    {% include "explorer/side_search.html" %}
  </div>

  <div class="col-md-9">
    <h3>{{ company.company|title }} {% if company.bus_type %}({{ company.bus_type }}){% endif %}</h3>
    <hr>

    <div class="row">
      <div class="col-md-6">
        <p class="lead">
          Contact Information
        </p>
        <ul class="list-unstyled">
          {% if contacts %}
            {% for contact in contacts %}
              {% if contact.contact_name is not none %}
              <li><span class="span-callout"><strong>{{ contact.contact_name|title }}</strong></span></li>
              {% endif %}
              {% if contact.address_1 is not none and contact.address_2 is not none %}
              <li>
                <span>
                  {{ contact.address_1|title }} <br>
                  {{ contact.address_2|title }}
                </span>
              </li>
              {% if contact.phone_number is not none %}
              <li><span>{{ contact.phone_number }}</span></li>
              {% endif %}
              {% if contact.email is not none %}
              <li><span><a href="mailto:{{ contact.email }}">{{ contact.email }}</a></span></li>
              {% endif %}
              <br>
              {% endif %}
            {% endfor %}
          {% else %}
            <p>No contact information available.</p>
          {% endif %}
        </ul>
      </div>
      <div class="col-md-6">
        <p class="lead">
          Contracts
        </p>
        <ul>
          {% for contract in company.contracts %}
          <li>
            <a href="{{ url_for('explorer.contracts', contract_id=contract.contract_id) }}">{{ contract.description|title }}</a>
          </li>
          {% endfor %}
        </ul>
      </div>

    </div>
  </div>
</div>
{% endblock %}

wexplorer/templates/explorer/contracts.html
{% extends "layout.html" %}
{% block content %}

<div class="row">
  <div class="col-md-3">
    {% include "explorer/side_search.html" %}
  </div>

  <div class="col-md-9">
    <h3>Contract for {{ contract.description|title }}</h3>
    <h5>Awarded to <a href="{{ url_for('explorer.companies', company_id=company.company_id) }}">{{ company.company|title }}</a></h5>

    <div class="row">
      <div class="col-md-12">
        <p class="lead">
          Contract Identification
        </p>
        <ul>
          {% if contract.type_of_contract is not none %}
          <li>
            <strong>Contract Type: </strong>
              {% if contract.type_of_contract|lower == 'county' %}
                {{ contract.type_of_contract }}
                {% if contract_href %} - <a href="{{ contract_href }}" target="_blank">View Contract</a>{% endif %}
              {% elif contract.type_of_contract|trim|lower == 'costars' %}
                {{ contract.type_of_contract }} - 
                Find COSTARS contracts on the state website <a href="http://www.costars.state.pa.us/SearchCOMember.aspx" target="_bank">here</a> and then click "Search Contracts" on the left.
              {% else %}
                {{ contract.type_of_contract }}
              {% endif %}
          </li>
          {% endif %}
          {% if contract.contract_number is not none %}
          <li><strong>Contract Number: </strong>{{ contract.contract_number }}</li>
          {% endif %}
          {% if contract.controller_number is not none %}
          <li><strong>Controller Number: </strong>{{ contract.controller_number }}</li>
          {% endif %}
          {% if contract.commcode is not none %}
          <li><strong>Commcode: </strong>{{ contract.commcode }}</li>
          {% endif %}
          {% if contract.expiration is not none %}
          <li><strong>Expiration: </strong>{{ contract.expiration.strftime('%Y-%m-%d') }}</li>
          {% endif %}
          {% if contract.notes is not none %}
          <li><strong>Notes: </strong>{{ contract.notes }}</li>
          {% endif %}

        </ul>
      </div>
    </div>
  </div>
</div>
{% endblock %}

wexplorer/templates/explorer/explore.html
{% extends "layout.html" %}
{% import "macros/render_pagination.html" as macros %}
{% block content %}

{% if not names %}
{% include "explorer/big_search.html" %}
{% endif %}

{% if names %}

<div class="row">
  <div class="col-md-3">
    {% include "explorer/side_search.html" %}
  </div>
  <div class="col-md-9">
    <h3 class="text-muted">
      {{ pagination.total_count }} results found for "{{ request.args.get('q') }}"
      {% if pagination.pages > 1 %}({{ (names | length) }} shown) {% endif %}<br>
      {% if last_updated %}<small>Last Updated: {% if last_updated %}{{ last_updated }}{% endif %}</small>{% endif %}
    </h3>
    <table class="table table-condensed" id="js-explore-search-results">
      <thead>
        <tr>
          <th class="js-sortable-th">Company</th>
          <th class="js-sortable-th">Contract Discription</th>
        </tr>
      </thead>
      <tbody>
        {% for name in names %}
        <tr>
          <td><a href="{{ url_for('explorer.companies', company_id=name.company_id) }}">{{ name.name|string|title }}</a></td>
          <td><a href="{{ url_for('explorer.contracts', contract_id=name.contract_id) }}">{{ name.description|string|title }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if pagination.pages > 1 %}
      {{ macros.render_pagination(pagination) }}
    {% endif %}
  </div>
</div>
{% elif names is none %}
<div class="row text-center">
  <h4>There are no results!</h4>
</div>
{% endif %}
{% endblock %}

wexplorer/templates/explorer/items.html
{% if purchases.items %}
<table class="table table-condensed table-five-items">
  <thead>
    <tr><th>Item</th></th>
  </thead>
  <tbody>
    {% for item in purchases.items %}
    <tr><td>{{ item.item }}</td></tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>Nothing here.</p>
{% endif %}

{% if purchases.pages > 1 %}
<ul class="pagination no-margin-pagination">
  {% if purchases.has_prev %}
  <li><a href="{{ url_for('explorer.companies', company_id=company.company_id, page=purchases.prev_num) }}">See previous</a></li>
  {% else %}
  <li class="disabled"><a href="">See previous</a></li>
  {% endif %}
  {% if purchases.has_next %}
  <li><a href="{{ url_for('explorer.companies', company_id=company.company_id, page=purchases.next_num) }}">See more</a></li>
  {% else %}
  <li class="disabled"><a href="">See more</a></li>
  {% endif %}
</ul>
{% endif %}

wexplorer/templates/explorer/side_search.html
<div class="sidebar side-nav">
  {% include "shared/logo.html" %}

  <form id="search-box" method="GET" class="form form-inline" action="/explore/" role="login">
    <div class="form-group">
      {{ form.q(placeholder="I'm looking for...", class_="form-control") }}
    </div>
    <input class="btn btn-default btn-success" type="submit" value="Search">
    <br><br>
    <ul class="nav nav-sidebar">

      <li>
        <label>Filter by:</label>
        <div class="checkbox checkbox-group">
          <label>
            {% if expired %}
            {{ form.expired(checked="checked") }}
            {% else %}
            {{ form.expired }}
            {% endif %}
            Expired Contracts
          </label>
        </div>
        <div class="checkbox checkbox-group">
          <label>
            {% if expiring %}
            {{ form.expiring(checked="checked") }}
            {% else %}
            {{ form.expiring }}
            {% endif %}
            Expiring Contracts
          </label>
        </div>
      </li>
    </ul>
  </form>
</div>

wexplorer/templates/explorer/upload_new.html
{% extends "layout.html" %}
{% import "macros.html" as macros %}

{% block content %}

<h2>Upload new data</h2>
<form method="POST" action="{{ url_for('explorer.upload') }}" enctype="multipart/form-data">

{{ form.csrf_token }}
<div class="form-group">
<label for="upload">Upload a file (must be .xls or .xlsx format)</label>
{{ macros.with_errors(form.upload) }}
</div>
<div class="form-group">
<label for="password">Enter the upload password:</label>
{{ macros.with_errors(form.password) }}
</div>

<input type="submit" class="btn btn-success" value="Upload">
</form>

{% endblock %}

wexplorer/templates/explorer/upload_success.html
{% extends "layout.html" %}
{% import "macros.html" as macros %}

{% block content %}

<div class="upload-error" hidden>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <span class="error-message">Something went wrong processing your file. The server says: </span>
  </div>
</div>

<div class="upload-processing">
  Upload processing...
</div>

<div class="upload-success" hidden>
  <h2>Upload successful</h2>
  <p><a href="{{ url_for('explorer.search') }}">Go Home</a></p>
</div>

{% endblock %}

{% block js %}

<script>
var filepath = '{{ filepath }}'

if (!filepath) {
  window.location.reload();
}

$.ajax({
  url: "{{ url_for('explorer.process_upload') }}",
  method: 'POST',
  data: { filepath: filepath },
  success: function(data, status, xhr) {
    $('.upload-processing').hide()
    $('.upload-success').show()
  }, error: function(xhr, status, error) {
    $('.upload-error').show()
    $('.error-message').append(error + ': ' + JSON.parse(xhr.responseText).message);
  }
})

</script>

{% endblock %}